### ISSUE TITLE
L K format 

### ISSUE THREAD

**Issue by emmanuel211g** [Mizogg/BITCOIN-WIF-Recovery#2]
How do i get this to work with compress keys. i Have a compress key missing characters

**Comment by Mizogg** [comment]
Hi I have updated another version that does all WIF's now 5 K and L I hope
you find what your looking for.

**Comment by emmanuel211g** [comment]
thank you so much. is there any way you can add muti cpu support or even gpu. i have10 characters missing.

**Comment by Mizogg** [comment]
All new Versions do max of 10 Missing WIF or HEX
