### ISSUE TITLE
Do this for Hex private key

### ISSUE THREAD

**Issue by Huntarh** [Mizogg/BITCOIN-WIF-Recovery#7]
Great work, this is exactly what I wanted, but can you do this for Hex private key also. Thanks

**Comment by Mizogg** [comment]
Thank you very much. I think it is a good idea I will look at making this with HEX.

**Comment by Mizogg** [comment]
Made it for HEX. But like the WIF can only do a max of 10 missing https://github.com/Mizogg/BITCOIN-WIF-Recovery/blob/main/WIF%26HEX/iceHEX_TXT.py
