### ISSUE TITLE
Error during the execution of > WIF_Recovery.py

### ISSUE THREAD

**Issue by RobGo88** [Mizogg/BITCOIN-WIF-Recovery#8]
Hello.
Unfortunately, I get the following error when running the program:

**************\WIF_Recovery.py", line 84, in <module> print(len(master_list))
OverflowError: cannot fit 'int' into an index-sized integer

Can you help me please?
Thanks Rob.

**Comment by Mizogg** [comment]
Hi Rob,

Yes I have seen this error. At the moment you can only look for 10 missing Characters any more than 10 you will get this error. This is something I working on. Hopefully updates soon
